### ISSUE TITLE
Don't wrap links with git.io

### ISSUE THREAD

**Issue by samueldr** [samueldr/github-to-irc#17]
As asked:

 * https://logs.nix.samueldr.com/nixos/2021-01-01#4421918;
 * https://logs.nix.samueldr.com/nixos/2021-01-01#1609531792-1609532209;
 
Comments?

This will remove the (somewhat) unneeded indirection, at the cost of bulking-up the appearance of the messages with long links.

**EDIT**: There are links to *commits* and *PRs*. These are only the events from GitHub.

**Comment by andir** [comment]
We can always use nixpkgs.dev/issues/<number> etc.. no?
I don't know if the bot also does link to specific commits or just issues and PRs.

**Comment by andir** [comment]
Oh, apparently it stopped working.. @zimbatm did you discontinue nixpkgs.dev?

**Comment by samueldr** [comment]
This is used for more than Nixpkgs outright. It's for the whole org, plus I recall it might be in use in non-NixOS channels.

**Comment by zimbatm** [comment]
@andir the right domain is nixpkgs.org
